GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{  
    "title": "breakfast",
    "author": "chef",
    "url": "www.foodchef.org",
    "likes": 647
}
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{  
    "name": "Seppo Talssssmaa",
    "number": "040-1231231"
}