GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhdHVwZWV0dSIsImlkIjoiNjQyMDFiZGI3N2FiMjM4ZWJkZTJjOGI2IiwiaWF0IjoxNjc5ODM3ODU1fQ.K585mkgm-kUbUS11ruOvml7-8kHW7la_rYXou6oCDdM

{  
    "title": "minunomablogi",
    "author": "mistermaister",
    "url": "www.omablogi.org",
    "likes": 622
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

 {
    "username": "apjhjss",
    "name": "chef",
    "password": "assasa212121"
  }
###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "aatupeetu",
    "password": "salainen"

}
###
DELETE http://localhost:3003/api/blogs/64204dda086b8bdf9d8facd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhdHVwZWV0dSIsImlkIjoiNjQyMDFiZGI3N2FiMjM4ZWJkZTJjOGI2IiwiaWF0IjoxNjc5ODM3ODU1fQ.K585mkgm-kUbUS11ruOvml7-8kHW7la_rYXou6oCDdM
